export * from "./home";
export * from "./general";
export * from "./loan";
export * from "./investments";
export * from "./assetManagement";
export * from "./about";
export * from "./loanForm";
export * from "./toastModal";
export * from "./investmentForm";
export * from "./faq";
export * from "./loanFormConfam";
export * from "./loanFormSmallBusiness";
export * from "./investmentFormDollar"